name: Testing
on: [push, pull_request]
jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v2
      
    - name: Use Node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Test
      run: npm test
